
services:
  app:
    container_name: nestjs-app
    image: nestjsapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped # Restart the container unless it is stopped manually
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_PROD: ${APP_PROD}
      PORT: ${PORT}
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL}

      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      JWT_AUTH: ${JWT_AUTH}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SALT_ROUNDS: ${SALT_ROUNDS}
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'

volumes:
  postgres-db:
    external: false
